version: '3.8'

services:
  app:
    # Constrói a imagem a partir do Dockerfile na pasta atual.
    # O Docker usará o seu arquivo `Dockerfile` existente.
    build: .
    container_name: imersao_devops_api
    # Mapeia a porta 8000 do contêiner para a porta 8000 da sua máquina.
    ports:
      - "8000:8000"
    # Monta o diretório atual no contêiner para refletir as mudanças no código em tempo real.
    # Isso também garante que o banco de dados SQLite (escola.db) seja salvo na sua máquina local.
    volumes:
      - .:/app